baseURL: "https://runtus.top/"
title: Runtus
paginate: 5
publishDir: "docs"
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
disqusShortname: goruntu
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Runtus
  description: "Daily life from Runtus"
  keywords: [Life, Portfolio, PaperMod]
  author: Runtus
  # author: ["Me", "You"] # multiple authors
  images: ["https://lao-lan-go.oss-cn-beijing.aliyuncs.com/highQua/pixiv34.JPG"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/avatar.png"
    favicon16x16: "/avatar.png"
    favicon32x32: "/avatar.png"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: The world from Runtus
    subtitle: "Record Daily Life"
    imageUrl: "/avatar.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Avatar
    buttons:
      - name: Posts
        url: /posts
      - name: Search
        url: /search

  socialIcons:
    - name: twitter
      url: "https://twitter.com/li8FfROBP2M9Dm8"
    - name: github
      url: "https://github.com/Runtus"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  

  # 自定义 friends
  friends:  
    - name: Lehr
      url: https://blog.imlehr.com
      avatar: https://lao-lan-go.oss-cn-beijing.aliyuncs.com/runtu_blog/Lehr.jpg
    - name: 何先森
      url: https://www.kevinmatt.top
      avatar: https://lao-lan-go.oss-cn-beijing.aliyuncs.com/runtu_blog/MrHe.png
    - name: 胡佬
      url: https://www.bencorn.com/
      avatar: https://lao-lan-go.oss-cn-beijing.aliyuncs.com/runtu_blog/shuisong.png
    - name: Yiyang Sun - 孙哥
      url: https://yysuen.me
      avatar: xxx

menu:
  main:
    - identifier: archives
      name: archives
      url: /archives/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search
      weight: 30
    - identifier: friends
      name: friends
      url: /friends
      weight: 30
    - identifier: github
      name: github
      url: https://github.com/Runtus
      weight: 40
    - identifier: 网易云
      name: 网易云转换
      url: /ncm
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true

outputs:
  home: 
    - HTML
    - RSS
    - JSON



  
